
ROBOT_TYPE: 72    # 机械臂型号-（一代机械臂api需要输入机械臂类型，二代机械臂api不需要输入类型，当前使用一代机械臂API，需要写机械臂型号） 常用机械臂类型对应数字如下

#RM65 = 65
#RML63_I = 631
#RML63_II = 632
#ECO65 = 651
#RM75 = 75
#ECO62 = 62
#GEN72 = 72

# 棋盘格参数
checkerboard_args:
  XX : 11 #标定板的中长度对应的角点的个数
  YY : 8  #标定板的中宽度对应的角点的个数
  L : 0.03 #标定板一格的长度  单位为米